<a href="https://colab.research.google.com/github/jukaLST/techdataanalysis/blob/main/task_5_12_24_JO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# DATAFRAME

df = pd.read_csv('/content/programming_basics21112024 (1).csv')

In [7]:
df
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [12]:
type(df["Name"])
df[["Name", "Age", "Sex"]]
df["Age"].median()

28.0

In [5]:
import pandas as pd

In [8]:
MAIN_DF = pd.read_csv("/content/programming_basics21112024 (1).csv")
df = MAIN_DF

In [9]:
df["Age"].median()

28.0

In [10]:
df["Sex"] = df["Sex"].replace({"male": 0, "female":1})

<ipython-input-10-c0a7928e4380>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Sex"] = df["Sex"].replace({"male": 0, "female":1})

In [12]:
df["Sex"].value_counts()

Sex
0    577
1    314
Name: count, dtype: int64

In [15]:
titanic_disaster = 1912
df["Year of birth"] = [titanic_disaster - age for age in df["Age"]]
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Year of birth
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,1890.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,1874.0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1886.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,1877.0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,1877.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,NaN,S,1885.0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,B42,S,1893.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,C148,C,1886.0
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,NaN,Q,1880.0

In [ ]:
function()

#print()
#type()

In [16]:
def printer():
  print("I AM ALIVE")

In [17]:
printer()

I AM ALIVE

In [18]:
def printer2(text):
  print(text)

In [19]:
printer2("la l sl s")

la l sl s

In [23]:
def substraction(num1, num2):
  print(num1-num2)

In [25]:
x = substraction(222,24)

198

In [28]:
text = Wa$sae*kk
text.replace("$", "").replace("*", "").lower().strip().title()

SyntaxError: invalid syntax (<ipython-input-28-0724a159cacf>, line 1)

In [ ]:
text2 = "GHGHFGHFGHFGHFfdfdf"
text2.replace

In [29]:
df = pd.DataFrame({"Name": ["Patryk", "Ola", "Ala"], "Points" : [1, 25, 50]})

In [30]:
df

     Name  Points
0  Patryk       1
1     Ola      25
2     Ala      50

In [33]:
def grade(points):
  if points > 45:
    return "A"
  elif points < 45 and points > 20:
    return "B"
  else:
    return "meh"

In [35]:
grade(17)

'meh'

In [38]:
df["Grade"] = df["Points"].apply(grade)
df

     Name  Points Grade
0  Patryk       1   meh
1     Ola      25     B
2     Ala      50     A

In [46]:
def rectangle_area(length, width):
  return length * width

In [47]:
rectangle_area(4, 5)

20

In [1]:
def is_even(number):
  if number % 2 == 0:
    print("even")
    return True
  else:
    return False

In [4]:
is_even(44)

even

True

In [6]:
def convert_to_celsius(temperature):
  return (temperature - 32)*5/9

In [7]:
convert_to_celsius(100)

37.77777777777778

In [12]:
import pandas as pd

my_data = pd.read_csv("/content/titanic.csv")
df = my_data.copy()

In [14]:
df["Over30"]=df['Age']>30
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Over30
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,True